Repository filletournesols/Petblr-social-network, pull requests merged in 2022-12, with the labels that each got.

#4 Nueva pull request (cambio de gmail por google y de % en margin top a rem)
  package.json
  src/addEventListener.js
  src/app/firebase.js
  src/index.html
  src/main.js
  src/style.css
Labels: documentation, enhancement

#5 firebase auth psw/email
  package.json
  src/addEventListener.js
  src/app/firebase.js
  src/app/register.js
  src/index.html
  src/main.js
  src/style.css
Labels: documentation, enhancement

#6 agregado texto "crear cuenta con"
  src/index.html
  src/style.css
Labels: documentation, enhancement

#8 Estilos de letras en el input
  src/index.html
  src/style.css
Labels: documentation

#9 Validación de contraseñas + agregado css
  src/app/register.js
  src/index.html
  src/main.js
  src/style.css
Labels: documentation, enhancement

#10 validación de correo
  src/app/register.js
  src/index.html
  src/main.js
Labels: enhancement

#11 Rama vic
  package.json
  src/addEventListener.js
  src/app/facebookrg.js
  src/app/firebase.js
  src/app/register.js
  src/index.html
  src/main.js
  src/style.css
Labels: documentation, enhancement

#12 Css login
  src/Assets/logo.png
  src/index.html
  src/style.css
Labels: documentation

#13 Router
  src/addEventListener.js
  src/app/register.js
  src/index.html
  src/js/router.js
  src/js/routes.js
  src/lib/index.js
  src/main.js
Labels: bug, documentation
