Repository filletournesols/Petblr-social-network, pull requests merged in 2023-01, with the labels that each got.

#14 Ramita test
  package.json
  src/app/facebookrg.js
  src/app/firebase.js
  src/app/register.js
  src/index.html
  src/js/router.js
  src/js/routes.js
  src/lib/index.js
  src/main.js
  src/style.css
  test/index.spec.js
Labels: documentation, enhancement

#15 responsive h1
  src/index.html
  src/js/routes.js
  src/style.css
Labels: documentation

#18 Nuevo Router
  package.json
  src/_redirects
  src/addEventListener.js
  src/app/register.js
  src/components/Feed.js
  src/components/Home.js
  src/components/Login.js
  src/components/Signup.js
  src/index.html
  src/js/router.js
  src/key.env
  src/lib/index.js
  src/main.js
  src/style.css
  test/index.spec.js
Labels: documentation, enhancement

#19 Estilos para archivo recoverpsw.js
  src/components/Email-login.js
  src/components/Login.js
  src/components/recoverpsw.js
  src/js/routes.js
  src/main.js
  src/style.css
Labels: documentation, enhancement

#22 Ramapara servicios firebase vic
  src/app/Psw-reset.js
  src/app/facebookrg.js
  src/app/setPersistence.js
  src/app/signOut.js
  src/components/Feed.js
  src/components/recoverpsw.js
Labels: documentation

#24 html y parte de css para el feed
  src/Assets/Petblr-blanco.png
  src/app/signOut.js
  src/components/Email-login.js
  src/components/Feed.js
  src/components/Home.js
  src/components/Login.js
  src/components/Signup.js
  src/components/recoverpsw.js
  src/index.html
  src/style.css
Labels: documentation, enhancement

#25 función setPersistence
  src/app/firebase.js
  src/app/setPersistence.js
Labels: bug, enhancement

#29 Test mock
  package.json
  src/app/PswReset.js
  src/app/firebase.js
  src/app/register.js
  src/app/setPersistence.js
  src/app/signIn.js
  src/components/EmailLogin.js
  src/components/recoverpsw.js
  src/main.js
  test/index.spec.js
Labels: documentation, enhancement

#30 Nuevas funciones para las historias de usuarios 4
  src/app/PswReset.js
  src/app/firebase.js
  src/app/register.js
  src/app/setDoc.js
  src/app/signOut.js
  src/components/Feed.js
Labels: documentation, enhancement

#32 Remita h ucuatro
  src/app/deletePost.js
  src/app/dislikePost.js
  src/app/firebase.js
  src/app/likePosts.js
  src/components/Signup.js
Labels: documentation, enhancement

#33 Tests + mocks
  src/app/PswReset.js
  src/app/getDoc.js
  src/app/register.js
  src/app/signOut.js
  src/components/Signup.js
  src/components/recoverpsw.js
  src/style.css
  test/index.spec.js
Labels: documentation, enhancement

#35 nuevos componentes
  src/app/addDoc.js
  src/app/firebase.js
  src/app/getDoc.js
  src/app/onAuthStateChanged.js
  src/app/register.js
  src/app/setDoc.js
  src/components/EmailLogin.js
  src/components/Feed.js
  src/components/Home.js
  src/components/Signup.js
  test/firebase.spec.js
Labels: documentation, enhancement

#38 arreglo
  src/app/deletePost.js
  src/app/likePosts.js
Labels: documentation, enhancement
